trigger:
  batch: true
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    displayName: Install dotnet
    inputs:
      packageType: "sdk"
      version: "7.0.x"

  - task: DotNetCoreCLI@2
    displayName: Lint
    inputs:
      command: "custom"
      custom: "format"
      arguments: "--verify-no-changes --verbosity diagnostic"

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: "build"
      arguments: "--configuration Release"

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: "test"
      arguments: >
        tests/Application.UnitTests
        --no-restore
        --verbosity normal
        --logger trx        
