services:
  sql:
    container_name: sql
    image: mcr.microsoft.com/azure-sql-edge
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
