services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=QWElkj132!
      - POSTGRES_USER=todos_user
      - POSTGRES_DB=todos_db
