name: Package

on:
  push:
    branches:
      - main
    paths:
      - "VSMA.csproj"
  workflow_dispatch:

jobs:
  publish:
    name: Publish to NuGet.org

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      - name: Create the package
        run: dotnet pack ProjectName.slnx -c Release -o ./nupkgs

      - name: Publish the package
        run: dotnet nuget push ./nupkgs/*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
