name: Package

on:
  push:
    branches:
      - main
    paths:
      - "VSMA.nuspec"
  workflow_dispatch:

jobs:
  publish:
    name: Publish to NuGet.org

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - uses: nuget/setup-nuget@v1
        name: Setup NuGet
        with:
          nuget-version: "latest"

      - name: Create the package
        run: dotnet pack ProjectName.sln -c Release -p:NuspecFile=~/VSMA.nuspec

      - name: Publish the package
        run: nuget push *.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}} -SkipDuplicate
